language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
env: PROTOBUF_VERSION=3.1.0

before_install:
  - ./install-protobuf.sh
  - PATH=/home/travis/bin:$PATH protoc --version
